// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmYBFkIj-fLlWvroN0JfdK5mzrxSpTfS4',
    appId: '1:542827107517:web:34af5403a89bc5f34b93d4',
    messagingSenderId: '542827107517',
    projectId: 'veggieswap-b01c0',
    authDomain: 'veggieswap-b01c0.firebaseapp.com',
    storageBucket: 'veggieswap-b01c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByT3t7MtR2CtfhNfGrQ3E-XZTjlAwqGyg',
    appId: '1:542827107517:android:a3c27289d9b317504b93d4',
    messagingSenderId: '542827107517',
    projectId: 'veggieswap-b01c0',
    storageBucket: 'veggieswap-b01c0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmYBFkIj-fLlWvroN0JfdK5mzrxSpTfS4',
    appId: '1:542827107517:web:5779051759b8512e4b93d4',
    messagingSenderId: '542827107517',
    projectId: 'veggieswap-b01c0',
    authDomain: 'veggieswap-b01c0.firebaseapp.com',
    storageBucket: 'veggieswap-b01c0.firebasestorage.app',
  );

}